### ISSUE TITLE
有内存泄漏的 问题我也没有查出 来是哪里出错了

### ISSUE THREAD

**Issue by seen2016** [xiaobailong24/MVVMArms#15]
![image](https://user-images.githubusercontent.com/22991894/50635486-5ad19200-0f8d-11e9-9de4-0eb9f1b32457.png)

**Comment by seen2016** [comment]
![image](https://user-images.githubusercontent.com/22991894/50635587-bf8cec80-0f8d-11e9-8600-cea274879dd2.png)
![image](https://user-images.githubusercontent.com/22991894/50635653-00850100-0f8e-11e9-81da-f43909fa3f14.png)

以上两处地方是不是重复了 ？如果不是重复，为什么要注册两次呢？我很疑惑！望大神能够指点迷津，谢谢！

**Comment by xiaobailong24** [comment]
1.这个输入法内存泄漏问题不大，系统问题
2.两个callback不是同一类型，作用也不一样

**Comment by seen2016** [comment]
> 1.这个输入法内存泄漏问题不大，系统问题
> 2.两个callback不是同一类型，作用也不一样

谢谢，大神指点！这个框架不错，如果能动态切换 baseurl就更好了！

**Comment by seen2016** [comment]
我擦，不小心关掉了

**Comment by xiaobailong24** [comment]
这个框架好久没更新了，有些问题，但有些地方可以参考下。
动态切换Url可以看下
https://github.com/JessYanCoding/RetrofitUrlManager
也可以多个Retrofit共用线程池和连接池，降低性能损耗

**Comment by seen2016** [comment]
> 这个框架好久没更新了，有些问题，但有些地方可以参考下。
> 动态切换Url可以看下
> https://github.com/JessYanCoding/RetrofitUrlManager
> 也可以多个Retrofit共用线程池和连接池，降低性能损耗

这个我好像看过，解决方案不错，在拦截器里作文章 ，至于多个 Retrofit ，有大神说资源浪费！
