### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by tututututututu** [xiaobailong24/MVVMArms#5]
我的一个UserViewModel 有如下的成员
public final ObservableField<UserBean> mUserViewModel = new ObservableField<>();
public final ObservableField<String> mDis = new ObservableField<>();
public final ObservableInt mCount = new ObservableInt();

和UI双向绑定之后,如果我想修改mDis的数据直接这样
viewModel.mDis.set("dis修改后");  //userViewModel是UserViewModel 类型
这样UI就会自动刷新

如果我想修改mUserViewModel 中的UserBean的数据,修改后UI不会自动刷新
我想到因为UserBean是一个单纯的实体类,所有没有被监听.
如果是让UserBean 去继承BaseObservable,写很多notify则破坏了实体类的单纯性.

不知道有没有什么办法解决这个绑定问题
3KS

**Comment by xiaobailong24** [comment]
@tututututututu 
```
public final ObservableField mUserViewModel = new ObservableField<>();
```
你的意思是不监听 **mUserViewModel** 的数据(UserBean)的变化？

**Comment by tututututututu** [comment]
@xiaobailong24 
我是想监听mUserViewModel 的数据(UserBean)的变化？
但是UserBean 是一个纯粹的实体类
如果我只是通过UserBean的set方法修改它的数据,UI没有刷新,我希望UI能够刷新

**Comment by tututututututu** [comment]
@xiaobailong24 可以加一下你的QQ或者微信吗

**Comment by xiaobailong24** [comment]
@tututututututu QQ:1406841392

**Comment by tututututututu** [comment]
@xiaobailong24 QQ有验证  你的真实姓名 @_@

**Comment by xiaobailong24** [comment]
@tututututututu Sorry,忘记了，我把验证关了。
