### ISSUE TITLE
demo apk is unavailable

### ISSUE THREAD

**Issue by sam453** [xiaobailong24/MVVMArms#6]
download url : 
 >https://github.com/xiaobailong24/MVVMArms/blob/master/image/MVVMArms.apk

**Comment by xiaobailong24** [comment]
@sam453 
Could not you download it?

![ae5 1f8jsphf 2 14 1zau2](https://user-images.githubusercontent.com/9431974/30733880-752a4b54-9fab-11e7-8223-0ee43350112f.png)

**Comment by sam453** [comment]
It's ok.

I was wrong，i downloaded it from >https://github.com/xiaobailong24/MVVMArms/blob/master/image/MVVMArms.apk

**Comment by xiaobailong24** [comment]
@sam453 OK
