### ISSUE TITLE
关于Dagger.Android在项目中的使用

### ISSUE THREAD

**Issue by akathink** [xiaobailong24/MVVMArms#8]
Hello：
最近在再看MVVM架构相关的一些东西，发现MVVMArms中含有Dagger.Android的库，但是里面却没有按照Dagger.Android的推荐方式去使用，是因为封装BaseActivity使用泛型有问题而不继承DaggerActivity的吗？

**Comment by xiaobailong24** [comment]
是的，继承的成本太高。
